name: Build GITS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}
    name: "Build GITS on ${{ matrix.os }}"

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build GITS
        shell: bash -el {0}
        run: |
          # https://github.com/intel/gits/blob/main/docs/building.md
          git clone https://github.com/intel/gits
          cd gits
          git lfs pull
          python -m venv ../venv
          ../venv/Scripts/activate.bat
          pip install -r requirements.txt
          mkdir build
          cd build
          cmake -A x64 ../
          cmake --build . --config Release
          cmake --install . --config Release --prefix ../../gits-install
